### PR TITLE
Add Italian translation.

### PR DESCRIPTION
**Pull request by igor-cali**

### CODE REVIEW

**Comment by igor-cali** [comment]
@apozas any issues not to merge this?

**Comment by apozas** [comment]
Hi Igor.

First of all, I noticed I didn't thank you earlier, so thanks a lot for the support and the translation.

There is no problem at all! Only that I would dedicate much time to the app that I do not currently have. I want to take a look at it before merging blindly, comparing it with the proposals in Crowdin. If everything goes well, on the weekend at the latest a new version will be released with Italian, German, Dutch and Catalan translations.

Thanks a lot!

**Comment by igor-cali** [comment]
Oh, ok. Sorry for pushing, I was not aware the app relies on external translation platforms like Crowdin.

**Comment by apozas** [comment]
No problem. I wanted to have it done this last weekend, but if you've been following the repo you'll have seen what's been going on. Don't you worry. In the end I will (maybe, possibly not) minor changes to this PR and merge it. But, in case you are interested, the project is [here](https://crowdin.com/project/contactdiary).

**Pull request merged**
